<?php
/**
 * HazmatTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.17.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HazmatTest Class Doc Comment
 *
 * @category    Class
 * @description This container is used by the seller to provide hazardous material information for the listing.&lt;br&gt;&lt;br&gt;Three elements are required to complete the Hazmat section of a listing:&lt;ul&gt;&lt;li&gt;&lt;b&gt;Pictograms&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;SignalWord&lt;/b&gt;&lt;/li&gt;&lt;li&gt;&lt;b&gt;Statements&lt;/b&gt;&lt;/li&gt;&lt;/ul&gt;&lt;br&gt;A fourth element, &lt;b&gt;Component&lt;/b&gt;, is optional.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HazmatTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Hazmat"
     */
    public function testHazmat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "component"
     */
    public function testPropertyComponent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pictograms"
     */
    public function testPropertyPictograms()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "signal_word"
     */
    public function testPropertySignalWord()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statements"
     */
    public function testPropertyStatements()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
